CREATE TABLE samples (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(256) NOT NULL
);

CREATE TABLE tasks (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) NOT NULL
);

CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL
);

CREATE TABLE genre (
  genreId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  genreName VARCHAR(256) NOT NULL
);

CREATE TABLE label (
  labelId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  labelName VARCHAR(256) NOT NULL
);